// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';
import {services} from '../models';

export function GetClient():Promise<github.Client>;

export function GetUser():Promise<github.ViewerInfo>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string):Promise<github.ViewerInfo>;

export function Logout():Promise<void>;

export function RegisterConsumer(arg1:services.ClientConsumer):Promise<void>;

export function SetClient(arg1:github.Client):Promise<void>;
