// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClient() {
  return window['go']['services']['AuthService']['GetClient']();
}

export function GetUser() {
  return window['go']['services']['AuthService']['GetUser']();
}

export function IsAuthenticated() {
  return window['go']['services']['AuthService']['IsAuthenticated']();
}

export function Login(arg1) {
  return window['go']['services']['AuthService']['Login'](arg1);
}

export function Logout() {
  return window['go']['services']['AuthService']['Logout']();
}

export function RegisterConsumer(arg1) {
  return window['go']['services']['AuthService']['RegisterConsumer'](arg1);
}

export function SetClient(arg1) {
  return window['go']['services']['AuthService']['SetClient'](arg1);
}
