// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function ClearAll():Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function GetNotifications(arg1:number):Promise<Array<storage.AppNotification>>;

export function GetUnreadCount():Promise<number>;

export function MarkAllRead():Promise<void>;

export function MarkRead(arg1:number):Promise<void>;
