// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAll() {
  return window['go']['services']['NotificationService']['ClearAll']();
}

export function Delete(arg1) {
  return window['go']['services']['NotificationService']['Delete'](arg1);
}

export function GetNotifications(arg1) {
  return window['go']['services']['NotificationService']['GetNotifications'](arg1);
}

export function GetUnreadCount() {
  return window['go']['services']['NotificationService']['GetUnreadCount']();
}

export function MarkAllRead() {
  return window['go']['services']['NotificationService']['MarkAllRead']();
}

export function MarkRead(arg1) {
  return window['go']['services']['NotificationService']['MarkRead'](arg1);
}
