// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCachedPRs(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetCachedPRs'](arg1, arg2);
}

export function GetMyPRs(arg1) {
  return window['go']['services']['PullRequestService']['GetMyPRs'](arg1);
}

export function GetMyRecentMerged(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetMyRecentMerged'](arg1, arg2);
}

export function GetReviewRequests(arg1) {
  return window['go']['services']['PullRequestService']['GetReviewRequests'](arg1);
}

export function GetReviewedByMe(arg1) {
  return window['go']['services']['PullRequestService']['GetReviewedByMe'](arg1);
}

export function GetTeamReviewRequests(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetTeamReviewRequests'](arg1, arg2);
}

export function MergePR(arg1, arg2) {
  return window['go']['services']['PullRequestService']['MergePR'](arg1, arg2);
}

export function RequestReviews(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['RequestReviews'](arg1, arg2, arg3);
}

export function SearchOrgMembers(arg1, arg2) {
  return window['go']['services']['PullRequestService']['SearchOrgMembers'](arg1, arg2);
}

export function SetClient(arg1) {
  return window['go']['services']['PullRequestService']['SetClient'](arg1);
}
