// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';
import {storage} from '../models';
import {time} from '../models';

export function AddLabels(arg1:string,arg2:Array<string>):Promise<void>;

export function AddPRComment(arg1:string,arg2:string):Promise<string>;

export function AddPRReviewComment(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function ApprovePR(arg1:string,arg2:string):Promise<void>;

export function GetCachedPRs(arg1:string,arg2:string):Promise<Array<github.PullRequest>>;

export function GetFileContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetFilesSinceCommit(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<github.PRFile>>;

export function GetMetricsHistory(arg1:number):Promise<Array<storage.MetricsSnapshot>>;

export function GetMyPRs(arg1:string):Promise<Array<github.PullRequest>>;

export function GetMyPRsAllReposPage(arg1:number,arg2:string):Promise<github.PRPage>;

export function GetMyPRsForRepoPage(arg1:string,arg2:string,arg3:number,arg4:string):Promise<github.PRPage>;

export function GetMyPRsPage(arg1:string,arg2:number,arg3:string):Promise<github.PRPage>;

export function GetMyRecentMerged(arg1:string,arg2:number):Promise<Array<github.PullRequest>>;

export function GetMyRecentMergedAllReposPage(arg1:number,arg2:number,arg3:string):Promise<github.PRPage>;

export function GetMyRecentMergedForRepoPage(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<github.PRPage>;

export function GetMyRecentMergedPage(arg1:string,arg2:number,arg3:number,arg4:string):Promise<github.PRPage>;

export function GetOrgMembers(arg1:string):Promise<Array<github.User>>;

export function GetPRCheckRuns(arg1:string):Promise<Array<github.CheckRun>>;

export function GetPRComments(arg1:string):Promise<github.PRComments>;

export function GetPRCommits(arg1:string):Promise<Array<github.PRCommit>>;

export function GetPRFiles(arg1:string,arg2:string,arg3:number):Promise<Array<github.PRFile>>;

export function GetRepoLabels(arg1:string,arg2:string):Promise<Array<github.Label>>;

export function GetReviewRequests(arg1:string):Promise<Array<github.PullRequest>>;

export function GetReviewRequestsAllReposPage(arg1:number,arg2:string):Promise<github.PRPage>;

export function GetReviewRequestsForRepoPage(arg1:string,arg2:string,arg3:number,arg4:string):Promise<github.PRPage>;

export function GetReviewRequestsPage(arg1:string,arg2:number,arg3:string):Promise<github.PRPage>;

export function GetReviewedByMe(arg1:string):Promise<Array<github.PullRequest>>;

export function GetReviewedByMeAllReposPage(arg1:number,arg2:string):Promise<github.PRPage>;

export function GetReviewedByMeForRepoPage(arg1:string,arg2:string,arg3:number,arg4:string):Promise<github.PRPage>;

export function GetReviewedByMePage(arg1:string,arg2:number,arg3:string):Promise<github.PRPage>;

export function GetSinglePR(arg1:string,arg2:string,arg3:number):Promise<github.PullRequest>;

export function GetSinglePRByNodeID(arg1:string):Promise<github.PullRequest>;

export function GetTeamReviewRequests(arg1:string,arg2:string):Promise<Array<github.PullRequest>>;

export function GetTeamReviewRequestsPage(arg1:string,arg2:string,arg3:number,arg4:string):Promise<github.PRPage>;

export function MarkReadyForReview(arg1:string):Promise<void>;

export function MergePR(arg1:string,arg2:string):Promise<string>;

export function RemoveLabels(arg1:string,arg2:Array<string>):Promise<void>;

export function ReplyToThread(arg1:string,arg2:string):Promise<string>;

export function RequestChangesPR(arg1:string,arg2:string):Promise<void>;

export function RequestReviews(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function ResolveThread(arg1:string):Promise<void>;

export function SearchOrgMembers(arg1:string,arg2:string):Promise<Array<github.User>>;

export function SetClient(arg1:github.Client):Promise<void>;

export function SubmitBatchReview(arg1:string,arg2:string,arg3:string,arg4:Array<github.DraftThread>):Promise<void>;

export function SyncOrgMembers(arg1:string):Promise<void>;

export function SyncOrgMembersIfStale(arg1:string,arg2:time.Duration):Promise<void>;

export function SyncTeamsForOrg(arg1:string):Promise<void>;

export function UnresolveThread(arg1:string):Promise<void>;
