// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';

export function GetCachedPRs(arg1:string,arg2:string):Promise<Array<github.PullRequest>>;

export function GetMyPRs(arg1:string):Promise<Array<github.PullRequest>>;

export function GetMyRecentMerged(arg1:string,arg2:number):Promise<Array<github.PullRequest>>;

export function GetReviewRequests(arg1:string):Promise<Array<github.PullRequest>>;

export function GetReviewedByMe(arg1:string):Promise<Array<github.PullRequest>>;

export function GetTeamReviewRequests(arg1:string,arg2:string):Promise<Array<github.PullRequest>>;

export function MergePR(arg1:string,arg2:string):Promise<void>;

export function RequestReviews(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function SearchOrgMembers(arg1:string,arg2:string):Promise<Array<github.User>>;

export function SetClient(arg1:github.Client):Promise<void>;
