// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLabels(arg1, arg2) {
  return window['go']['services']['PullRequestService']['AddLabels'](arg1, arg2);
}

export function AddPRReviewComment(arg1, arg2, arg3, arg4) {
  return window['go']['services']['PullRequestService']['AddPRReviewComment'](arg1, arg2, arg3, arg4);
}

export function ApprovePR(arg1, arg2) {
  return window['go']['services']['PullRequestService']['ApprovePR'](arg1, arg2);
}

export function GetCachedPRs(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetCachedPRs'](arg1, arg2);
}

export function GetFileContent(arg1, arg2, arg3, arg4) {
  return window['go']['services']['PullRequestService']['GetFileContent'](arg1, arg2, arg3, arg4);
}

export function GetMetricsHistory(arg1) {
  return window['go']['services']['PullRequestService']['GetMetricsHistory'](arg1);
}

export function GetMyPRs(arg1) {
  return window['go']['services']['PullRequestService']['GetMyPRs'](arg1);
}

export function GetMyPRsAllReposPage(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetMyPRsAllReposPage'](arg1, arg2);
}

export function GetMyPRsForRepoPage(arg1, arg2, arg3, arg4) {
  return window['go']['services']['PullRequestService']['GetMyPRsForRepoPage'](arg1, arg2, arg3, arg4);
}

export function GetMyPRsPage(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['GetMyPRsPage'](arg1, arg2, arg3);
}

export function GetMyRecentMerged(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetMyRecentMerged'](arg1, arg2);
}

export function GetMyRecentMergedAllReposPage(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['GetMyRecentMergedAllReposPage'](arg1, arg2, arg3);
}

export function GetMyRecentMergedForRepoPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['PullRequestService']['GetMyRecentMergedForRepoPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetMyRecentMergedPage(arg1, arg2, arg3, arg4) {
  return window['go']['services']['PullRequestService']['GetMyRecentMergedPage'](arg1, arg2, arg3, arg4);
}

export function GetOrgMembers(arg1) {
  return window['go']['services']['PullRequestService']['GetOrgMembers'](arg1);
}

export function GetPRCheckRuns(arg1) {
  return window['go']['services']['PullRequestService']['GetPRCheckRuns'](arg1);
}

export function GetPRComments(arg1) {
  return window['go']['services']['PullRequestService']['GetPRComments'](arg1);
}

export function GetPRCommits(arg1) {
  return window['go']['services']['PullRequestService']['GetPRCommits'](arg1);
}

export function GetPRFiles(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['GetPRFiles'](arg1, arg2, arg3);
}

export function GetRepoLabels(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetRepoLabels'](arg1, arg2);
}

export function GetReviewRequests(arg1) {
  return window['go']['services']['PullRequestService']['GetReviewRequests'](arg1);
}

export function GetReviewRequestsAllReposPage(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetReviewRequestsAllReposPage'](arg1, arg2);
}

export function GetReviewRequestsForRepoPage(arg1, arg2, arg3, arg4) {
  return window['go']['services']['PullRequestService']['GetReviewRequestsForRepoPage'](arg1, arg2, arg3, arg4);
}

export function GetReviewRequestsPage(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['GetReviewRequestsPage'](arg1, arg2, arg3);
}

export function GetReviewedByMe(arg1) {
  return window['go']['services']['PullRequestService']['GetReviewedByMe'](arg1);
}

export function GetReviewedByMeAllReposPage(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetReviewedByMeAllReposPage'](arg1, arg2);
}

export function GetReviewedByMeForRepoPage(arg1, arg2, arg3, arg4) {
  return window['go']['services']['PullRequestService']['GetReviewedByMeForRepoPage'](arg1, arg2, arg3, arg4);
}

export function GetReviewedByMePage(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['GetReviewedByMePage'](arg1, arg2, arg3);
}

export function GetSinglePR(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['GetSinglePR'](arg1, arg2, arg3);
}

export function GetSinglePRByNodeID(arg1) {
  return window['go']['services']['PullRequestService']['GetSinglePRByNodeID'](arg1);
}

export function GetTeamReviewRequests(arg1, arg2) {
  return window['go']['services']['PullRequestService']['GetTeamReviewRequests'](arg1, arg2);
}

export function GetTeamReviewRequestsPage(arg1, arg2, arg3, arg4) {
  return window['go']['services']['PullRequestService']['GetTeamReviewRequestsPage'](arg1, arg2, arg3, arg4);
}

export function MarkReadyForReview(arg1) {
  return window['go']['services']['PullRequestService']['MarkReadyForReview'](arg1);
}

export function MergePR(arg1, arg2) {
  return window['go']['services']['PullRequestService']['MergePR'](arg1, arg2);
}

export function RemoveLabels(arg1, arg2) {
  return window['go']['services']['PullRequestService']['RemoveLabels'](arg1, arg2);
}

export function RequestChangesPR(arg1, arg2) {
  return window['go']['services']['PullRequestService']['RequestChangesPR'](arg1, arg2);
}

export function RequestReviews(arg1, arg2, arg3) {
  return window['go']['services']['PullRequestService']['RequestReviews'](arg1, arg2, arg3);
}

export function ResolveThread(arg1) {
  return window['go']['services']['PullRequestService']['ResolveThread'](arg1);
}

export function SearchOrgMembers(arg1, arg2) {
  return window['go']['services']['PullRequestService']['SearchOrgMembers'](arg1, arg2);
}

export function SetClient(arg1) {
  return window['go']['services']['PullRequestService']['SetClient'](arg1);
}

export function SyncOrgMembers(arg1) {
  return window['go']['services']['PullRequestService']['SyncOrgMembers'](arg1);
}

export function SyncOrgMembersIfStale(arg1, arg2) {
  return window['go']['services']['PullRequestService']['SyncOrgMembersIfStale'](arg1, arg2);
}

export function SyncTeamsForOrg(arg1) {
  return window['go']['services']['PullRequestService']['SyncTeamsForOrg'](arg1);
}

export function UnresolveThread(arg1) {
  return window['go']['services']['PullRequestService']['UnresolveThread'](arg1);
}
