// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';
import {storage} from '../models';
import {time} from '../models';

export function ApprovePR(arg1:string,arg2:string):Promise<void>;

export function GetCachedPRs(arg1:string,arg2:string):Promise<Array<github.PullRequest>>;

export function GetMetricsHistory(arg1:number):Promise<Array<storage.MetricsSnapshot>>;

export function GetMyPRs(arg1:string):Promise<Array<github.PullRequest>>;

export function GetMyPRsPage(arg1:string,arg2:number,arg3:string):Promise<github.PRPage>;

export function GetMyRecentMerged(arg1:string,arg2:number):Promise<Array<github.PullRequest>>;

export function GetMyRecentMergedPage(arg1:string,arg2:number,arg3:number,arg4:string):Promise<github.PRPage>;

export function GetOrgMembers(arg1:string):Promise<Array<github.User>>;

export function GetPRCheckRuns(arg1:string):Promise<Array<github.CheckRun>>;

export function GetPRComments(arg1:string):Promise<github.PRComments>;

export function GetReviewRequests(arg1:string):Promise<Array<github.PullRequest>>;

export function GetReviewRequestsPage(arg1:string,arg2:number,arg3:string):Promise<github.PRPage>;

export function GetReviewedByMe(arg1:string):Promise<Array<github.PullRequest>>;

export function GetReviewedByMePage(arg1:string,arg2:number,arg3:string):Promise<github.PRPage>;

export function GetSinglePR(arg1:string,arg2:string,arg3:number):Promise<github.PullRequest>;

export function GetTeamReviewRequests(arg1:string,arg2:string):Promise<Array<github.PullRequest>>;

export function GetTeamReviewRequestsPage(arg1:string,arg2:string,arg3:number,arg4:string):Promise<github.PRPage>;

export function MergePR(arg1:string,arg2:string):Promise<void>;

export function RequestReviews(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function SearchOrgMembers(arg1:string,arg2:string):Promise<Array<github.User>>;

export function SetClient(arg1:github.Client):Promise<void>;

export function SyncOrgMembers(arg1:string):Promise<void>;

export function SyncOrgMembersIfStale(arg1:string,arg2:time.Duration):Promise<void>;

export function SyncTeamsForOrg(arg1:string):Promise<void>;
