// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {github} from '../models';
import {context} from '../models';
import {gitutil} from '../models';

export function AddRepo():Promise<storage.TrackedRepo>;

export function AddRepoFromPath(arg1:string):Promise<storage.TrackedRepo>;

export function GetTrackedRepoByID(arg1:number):Promise<storage.TrackedRepo>;

export function GetTrackedRepos():Promise<Array<storage.TrackedRepo>>;

export function RemoveRepo(arg1:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetClient(arg1:github.Client):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ValidateGitRepo(arg1:string):Promise<gitutil.RepoInfo>;
