// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo() {
  return window['go']['services']['RepoService']['AddRepo']();
}

export function AddRepoFromPath(arg1) {
  return window['go']['services']['RepoService']['AddRepoFromPath'](arg1);
}

export function GetTrackedRepoByID(arg1) {
  return window['go']['services']['RepoService']['GetTrackedRepoByID'](arg1);
}

export function GetTrackedRepos() {
  return window['go']['services']['RepoService']['GetTrackedRepos']();
}

export function RemoveRepo(arg1) {
  return window['go']['services']['RepoService']['RemoveRepo'](arg1);
}

export function SelectFolder() {
  return window['go']['services']['RepoService']['SelectFolder']();
}

export function SetClient(arg1) {
  return window['go']['services']['RepoService']['SetClient'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['RepoService']['SetContext'](arg1);
}

export function SetRepoAIAgent(arg1, arg2) {
  return window['go']['services']['RepoService']['SetRepoAIAgent'](arg1, arg2);
}

export function ValidateGitRepo(arg1) {
  return window['go']['services']['RepoService']['ValidateGitRepo'](arg1);
}
