// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function AddTrackedOrg(arg1:string):Promise<void>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTrackedOrgs():Promise<Array<string>>;

export function GetTrackedTeams(arg1:string):Promise<Array<storage.TrackedTeam>>;

export function RemoveTrackedOrg(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetTeamEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;
