// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function AddReviewPriority(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddTrackedOrg(arg1:string):Promise<void>;

export function GetReviewPriorities(arg1:string):Promise<Array<storage.ReviewPriority>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTrackedOrgs():Promise<Array<string>>;

export function GetTrackedTeams(arg1:string):Promise<Array<storage.TrackedTeam>>;

export function RemoveReviewPriority(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveTrackedOrg(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetTeamEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateReviewPriorityOrder(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;
