// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrackedOrg(arg1:string):Promise<void>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTrackedOrgs():Promise<Array<string>>;

export function RemoveTrackedOrg(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
