// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrackedOrg(arg1) {
  return window['go']['services']['SettingsService']['AddTrackedOrg'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['services']['SettingsService']['GetSetting'](arg1);
}

export function GetTrackedOrgs() {
  return window['go']['services']['SettingsService']['GetTrackedOrgs']();
}

export function RemoveTrackedOrg(arg1) {
  return window['go']['services']['SettingsService']['RemoveTrackedOrg'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['services']['SettingsService']['SetSetting'](arg1, arg2);
}
