// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelClaudeReview() {
  return window['go']['services']['WorkspaceService']['CancelClaudeReview']();
}

export function CheckToolAvailability() {
  return window['go']['services']['WorkspaceService']['CheckToolAvailability']();
}

export function CheckoutPR(arg1, arg2, arg3) {
  return window['go']['services']['WorkspaceService']['CheckoutPR'](arg1, arg2, arg3);
}

export function DeleteAIReview(arg1) {
  return window['go']['services']['WorkspaceService']['DeleteAIReview'](arg1);
}

export function GetAIReview(arg1) {
  return window['go']['services']['WorkspaceService']['GetAIReview'](arg1);
}

export function GetCurrentBranch(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['GetCurrentBranch'](arg1, arg2);
}

export function GetDefaultClaudePrompt() {
  return window['go']['services']['WorkspaceService']['GetDefaultClaudePrompt']();
}

export function OpenTerminal(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['OpenTerminal'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['WorkspaceService']['SetContext'](arg1);
}

export function StartAIReview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['WorkspaceService']['StartAIReview'](arg1, arg2, arg3, arg4, arg5);
}
