// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPRDescription(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['ApplyPRDescription'](arg1, arg2, arg3, arg4);
}

export function CancelAIReview() {
  return window['go']['services']['WorkspaceService']['CancelAIReview']();
}

export function CancelGenerateDescription() {
  return window['go']['services']['WorkspaceService']['CancelGenerateDescription']();
}

export function CheckToolAvailability() {
  return window['go']['services']['WorkspaceService']['CheckToolAvailability']();
}

export function CheckoutPR(arg1, arg2, arg3) {
  return window['go']['services']['WorkspaceService']['CheckoutPR'](arg1, arg2, arg3);
}

export function DeleteAIReview(arg1) {
  return window['go']['services']['WorkspaceService']['DeleteAIReview'](arg1);
}

export function GetAIReview(arg1) {
  return window['go']['services']['WorkspaceService']['GetAIReview'](arg1);
}

export function GetCurrentBranch(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['GetCurrentBranch'](arg1, arg2);
}

export function GetDefaultDescriptionPrompt() {
  return window['go']['services']['WorkspaceService']['GetDefaultDescriptionPrompt']();
}

export function GetDefaultReviewPrompt() {
  return window['go']['services']['WorkspaceService']['GetDefaultReviewPrompt']();
}

export function OpenTerminal(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['OpenTerminal'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['WorkspaceService']['SetContext'](arg1);
}

export function StartAIReview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['WorkspaceService']['StartAIReview'](arg1, arg2, arg3, arg4, arg5);
}

export function StartGenerateDescription(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['StartGenerateDescription'](arg1, arg2, arg3, arg4);
}
