// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendCodeTourToDescription(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['AppendCodeTourToDescription'](arg1, arg2, arg3, arg4);
}

export function ApplyPRDescription(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['ApplyPRDescription'](arg1, arg2, arg3, arg4);
}

export function ApplyPRTitle(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['ApplyPRTitle'](arg1, arg2, arg3, arg4);
}

export function CancelAIReview() {
  return window['go']['services']['WorkspaceService']['CancelAIReview']();
}

export function CancelAISummary() {
  return window['go']['services']['WorkspaceService']['CancelAISummary']();
}

export function CancelCodeTour() {
  return window['go']['services']['WorkspaceService']['CancelCodeTour']();
}

export function CancelGenerateDescription() {
  return window['go']['services']['WorkspaceService']['CancelGenerateDescription']();
}

export function CancelGenerateTitle() {
  return window['go']['services']['WorkspaceService']['CancelGenerateTitle']();
}

export function CheckToolAvailability() {
  return window['go']['services']['WorkspaceService']['CheckToolAvailability']();
}

export function CheckoutPR(arg1, arg2, arg3) {
  return window['go']['services']['WorkspaceService']['CheckoutPR'](arg1, arg2, arg3);
}

export function DeleteAIReview(arg1) {
  return window['go']['services']['WorkspaceService']['DeleteAIReview'](arg1);
}

export function DeleteAISummary(arg1) {
  return window['go']['services']['WorkspaceService']['DeleteAISummary'](arg1);
}

export function DeleteCodeTour(arg1) {
  return window['go']['services']['WorkspaceService']['DeleteCodeTour'](arg1);
}

export function GetAIReview(arg1) {
  return window['go']['services']['WorkspaceService']['GetAIReview'](arg1);
}

export function GetAISummary(arg1) {
  return window['go']['services']['WorkspaceService']['GetAISummary'](arg1);
}

export function GetCodeTour(arg1) {
  return window['go']['services']['WorkspaceService']['GetCodeTour'](arg1);
}

export function GetCurrentBranch(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['GetCurrentBranch'](arg1, arg2);
}

export function GetDefaultDescriptionPrompt() {
  return window['go']['services']['WorkspaceService']['GetDefaultDescriptionPrompt']();
}

export function GetDefaultReviewPrompt() {
  return window['go']['services']['WorkspaceService']['GetDefaultReviewPrompt']();
}

export function GetDefaultTitlePrompt() {
  return window['go']['services']['WorkspaceService']['GetDefaultTitlePrompt']();
}

export function OpenTerminal(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['OpenTerminal'](arg1, arg2);
}

export function SetCodeTourCommentID(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['SetCodeTourCommentID'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['WorkspaceService']['SetContext'](arg1);
}

export function StartAIReview(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['StartAIReview'](arg1, arg2, arg3, arg4);
}

export function StartAISummary(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['StartAISummary'](arg1, arg2, arg3, arg4);
}

export function StartCodeTour(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['StartCodeTour'](arg1, arg2, arg3, arg4);
}

export function StartGenerateDescription(arg1, arg2, arg3) {
  return window['go']['services']['WorkspaceService']['StartGenerateDescription'](arg1, arg2, arg3);
}

export function StartGenerateTitle(arg1, arg2, arg3, arg4) {
  return window['go']['services']['WorkspaceService']['StartGenerateTitle'](arg1, arg2, arg3, arg4);
}
