// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function ApplyPRDescription(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function CancelAIReview():Promise<void>;

export function CancelGenerateDescription():Promise<void>;

export function CheckToolAvailability():Promise<services.ToolAvailability>;

export function CheckoutPR(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DeleteAIReview(arg1:string):Promise<void>;

export function GetAIReview(arg1:string):Promise<services.AIReviewResult>;

export function GetCurrentBranch(arg1:string,arg2:string):Promise<string>;

export function GetDefaultDescriptionPrompt():Promise<string>;

export function GetDefaultReviewPrompt():Promise<string>;

export function OpenTerminal(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartAIReview(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<void>;

export function StartGenerateDescription(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;
