// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartPoller() {
  return window['go']['main']['App']['StartPoller']();
}

export function StopPoller() {
  return window['go']['main']['App']['StopPoller']();
}
