// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImageProxyMiddleware() {
  return window['go']['main']['App']['ImageProxyMiddleware']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetPollInterval(arg1) {
  return window['go']['main']['App']['SetPollInterval'](arg1);
}

export function StartPoller() {
  return window['go']['main']['App']['StartPoller']();
}

export function StopPoller() {
  return window['go']['main']['App']['StopPoller']();
}

export function SyncOrgMembers(arg1) {
  return window['go']['main']['App']['SyncOrgMembers'](arg1);
}
