// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartPoller():Promise<void>;

export function StopPoller():Promise<void>;

export function SyncOrgMembers(arg1:string):Promise<void>;
