// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImageProxyMiddleware():Promise<any>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetPollInterval(arg1:number):Promise<void>;

export function StartPoller():Promise<void>;

export function StopPoller():Promise<void>;

export function SyncOrgMembers(arg1:string):Promise<void>;
